#!/bin/bash
# Generate a labeled, non-production test vault fixture using the CLI + a fixed
# fixture password. Fixture secrets carry obvious markers and are NOT real.
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/env.sh

OUT="${1:-Fixtures/ValidVaults/basic-vault}"
PASSWORD="example-password-not-real"

swift build --product zyquo-vault-cli >/dev/null
BIN=$(swift build --show-bin-path)

rm -rf "$OUT"
# The CLI has no create command (safe commands only, §10.13); use the test
# support entry point via swift run of a tiny inline generator is not available
# either — so fixtures are produced by the integration test suite. This script
# validates an existing fixture or explains how to refresh it.
if [ -d "$OUT" ]; then
    "$BIN/zyquo-vault-cli" vault info "$OUT"
    echo "$PASSWORD" | "$BIN/zyquo-vault-cli" vault verify "$OUT"
else
    echo "note: fixture absent. Fixtures are generated by the integration tests"
    echo "      (VaultLifecycleTests) into temp dirs; persisting one here will be"
    echo "      added with M2's record support so the fixture is meaningful."
fi
